### ISSUE TITLE
Adding content

### ISSUE THREAD

**Issue by clyne** [NCAR/vast#2]
A couple of questions on adding new content:

1. Is there any significance to the "labels" in the headers of the _index.md files? For example, in about/_index.md:

```
---
title: "Visualization and Analysis Software and Technology"
date: 2022-04-22T00:00:00+06:00
mission : "VAST's mission is to ..."
description : "More and more about VAST..."
---
```

Do "mission" and "description" have any meeting (keywords), or are they completely arbitrary?

2. How does one simply add markdown to an _index.md file? If I try adding text below the above header it seems to be ignored (However, DART's publication text includes markdown text his way)?

**Comment by kmpaul** [comment]
> 1. Is there any significance to the "labels" in the headers of the _index.md files? For example, in about/_index.md:

They are significant. They are referenced in the Hugo templates by name.

**Comment by kmpaul** [comment]
> How does one simply add markdown to an _index.md file? If I try adding text below the above header it seems to be ignored (However, DART's publication text includes markdown text his way)?

I think it depends on the template/page. That’s partly what makes this a bit of a mess. Sorry.

**Comment by kmpaul** [comment]
Check out the new CONTRIBUTING.md file.  I've tried to update it after cleaning up the repo.

**Comment by clyne** [comment]
MUCH more helpful. Thank you. However, when I try to add content to the education section nothing shows up. No problem making updates to the other sections so far.

**Comment by clyne** [comment]
Ditto for Services. Actually, I'm not really sure that I understand what to do to  add content to services. There is a separate `data` section for services, and I don't understand the distinction between "site pages" and "site data". Or at least I don't understand why Services has a `data` entry, and Education does not.

**Comment by kmpaul** [comment]
Okay, the education and services pages now display their content properly with the merge of #15.  So, this should be fixable.  The education content is now displaying on the main page (https://ncar.github.io/vast/education/).  And the services content should display, once that is added.

**Comment by kmpaul** [comment]
As for the differences between data and "content pages"...

It all depends on the layout/template used for the page.  To really understand it, you need to look into the `themes/ncar/layouts` folder and look at all of the different template HTML files.  If a template file says something like `{{ with .Site.Data.services }}` at the top of the file, then it is pulling data/content from the `data/services.yml`.  If it doesn't say anything like this at the top of the template, then it gets its data from the `.md` file that defines the content of the page.

I know it's confusing.  I'm not a fan of how it is structured because there really isn't any reliable way of knowing what pages get there content from where, except in the template HTML files (layouts).  And that's a bit like saying "read the code".

I'll add some more detail to the `CONTRIBUTING.md` document to try to clarify where each page get's its content.
