### ISSUE TITLE
Software page updates

### ISSUE THREAD

**Issue by clyne** [NCAR/vast#9]
The Software entries for VAPOR and GeoCAT should have appropriate images, and the text can be modified as you see fit.

**Comment by clyne** [comment]
Also, be sure to click on "details" and review and update to. your preferences

**Comment by erogluorhan** [comment]
As GeoCAT itself is not a software product, I am planning to 

- Link to the GeoCAT homepage for the "Documentation" button
- Link to the GeoCAT-examples repo via the "Github" button to greet the reader with the vis gallery repo (Linking to GeoCAT-comp is an alternative, too) since linking to https://github.com/NCAR/GeoCAT, which generates our GeoCAT website, wouldn't make much sense.
- Put clear information into the description text about all these

Please let me know if that makes sense

**Comment by clyne** [comment]
Sounds good!
